language: ruby
cache: bundler
sudo: false
rvm:
  - 1.9.3 # when removed, get rid of the before_script hack and also the one in application_generator.rb
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.0
env:
  - RAILS_VERSION="~> 4.2.0"
before_script:
  - "[ $TRAVIS_RUBY_VERSION = \"1.9.3\" ] && travis_retry gem install mime-types --version \"~> 2\" || true"
  - travis_retry gem install rails --version "$RAILS_VERSION"
