language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head
env:
  - RAILS_VERSION="~> 4.2.0"
  - RAILS_VERSION="~> 5.0.0"
  - RAILS_VERSION="~> 5.1.0"
  - RAILS_VERSION="~> 5.2.0"
  - RAILS_VERSION="~> 6.0.0.rc1"
matrix:
  exclude:
    - rvm: 2.4.6
      env: RAILS_VERSION="~> 6.0.0.rc1"
    - rvm: 2.6.3
      env: RAILS_VERSION="~> 4.2.0"
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install:
  - gem update --system 3.0.3
  - gem uninstall bundler && gem install bundler -v 1.17.3
before_script:
  - travis_retry gem install rails --version "$RAILS_VERSION"
